# Generated by Django 3.1.5 on 2021-02-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='account',
            new_name='debitaccount',
        ),
    ]
