# Generated by Django 3.1.5 on 2021-02-19 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0006_contributionimport_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contribution",
            options={
                "ordering": ["-date"],
                "verbose_name": "Contribution",
                "verbose_name_plural": "Contributions",
            },
        ),
        migrations.AlterField(
            model_name="contribution",
            name="_import",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="contributions.contributionimport",
            ),
        ),
    ]
