# Generated by Django 3.1.5 on 2021-03-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_auto_20210219_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributionimport',
            options={'ordering': ['-date'], 'verbose_name': 'Contribution Import', 'verbose_name_plural': 'Contributions Imports'},
        ),
    ]
