# Generated by Django 3.1.5 on 2021-03-04 08:04

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0008_auto_20210301_1153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributionimport",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="contributionimport",
            name="importfile",
            field=models.FileField(upload_to="", verbose_name="Importfile"),
        ),
    ]
