# Generated by Django 3.1 on 2020-11-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201105_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naturalperson',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Natural Person', 'verbose_name_plural': 'Natural Persons'},
        ),
    ]
