# Generated by Django 3.1 on 2020-11-21 08:32

from django.db import migrations


class Migration(migrations.Migration):
    def create_initial_organization(apps, schema_editor):
        import datetime

        JuristicPerson = apps.get_model("core.JuristicPerson")
        if not JuristicPerson.objects.filter(id=1).exists():
            JuristicPerson.objects.create(
                id=1, name="Your organization's name", created=datetime.datetime.now()
            )

    dependencies = [
        ("core", "0011_person_created"),
    ]

    operations = [
        migrations.RunPython(create_initial_organization, migrations.RunPython.noop)
    ]
