# Generated by Django 3.1 on 2020-11-23 11:38

from django.db import migrations


class Migration(migrations.Migration):
    def create_category(apps, schema_editor):
        Category = apps.get_model("core.Category")
        Category.objects.create(name="Address origin", slug="addressorigin")

    dependencies = [
        ("core", "0015_web"),
    ]

    operations = [migrations.RunPython(create_category, migrations.RunPython.noop)]
