# Generated by Django 3.1 on 2020-09-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20200813_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='postal',
            name='city',
            field=models.TextField(default='', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='postal',
            name='postcode',
            field=models.TextField(default='', verbose_name='Post Code'),
        ),
    ]
