# Generated by Django 3.1.1 on 2020-09-25 13:58

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200903_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of county or state')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abbreviation')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.person')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
            bases=('person.person',),
        ),
        migrations.CreateModel(
            name='LegalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name for legal type')),
            ],
            options={
                'verbose_name': 'Legal type',
                'verbose_name_plural': 'Legal types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.person')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('profession', models.CharField(max_length=255, verbose_name='profession')),
            ],
            bases=('person.person',),
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name for phone type')),
            ],
            options={
                'verbose_name': 'Phone type',
                'verbose_name_plural': 'Phone types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='salutation',
            field=models.CharField(max_length=255, null=True, verbose_name='Salutation'),
        ),
        migrations.AddField(
            model_name='person',
            name='salutation_letter',
            field=models.CharField(max_length=255, null=True, verbose_name='Salutation Letter'),
        ),
        migrations.AddField(
            model_name='postal',
            name='pobox_city',
            field=models.TextField(default='', verbose_name='POBox City'),
        ),
        migrations.AddField(
            model_name='postal',
            name='pobox_name',
            field=models.TextField(default='', verbose_name='POBox Name'),
        ),
        migrations.AddField(
            model_name='postal',
            name='pobox_postcode',
            field=models.TextField(default='', verbose_name='POBox Post Code'),
        ),
        migrations.AddField(
            model_name='postal',
            name='supplemental_address',
            field=models.TextField(default='', verbose_name='Supplemental Address'),
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='person.person')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.legaltype')),
            ],
            bases=('person.person',),
        ),
        migrations.AddField(
            model_name='postal',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.county'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.phonetype'),
        ),
    ]
