# Generated by Django 3.1.1 on 2020-09-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20200925_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='abbreviation_key',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='connect_key',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='legacy_key',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
    ]
