# Generated by Django 3.1.1 on 2020-09-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20200925_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, verbose_name='Term')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.category')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.ForeignKey(limit_choices_to={'category__slug': 'addressstatus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_email_status', to='person.term'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='gender',
            field=models.ForeignKey(limit_choices_to={'category__slug': 'gender'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender', to='person.term'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='title',
            field=models.ForeignKey(limit_choices_to={'category__slug': 'title'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title', to='person.term'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.ForeignKey(limit_choices_to={'category__slug': 'personstatus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personstatus', to='person.term'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.ForeignKey(limit_choices_to={'category__slug': 'addressstatus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_phone_status', to='person.term'),
        ),
        migrations.AlterField(
            model_name='postal',
            name='status',
            field=models.ForeignKey(limit_choices_to={'category__slug': 'addressstatus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_postal_status', to='person.term'),
        ),
        migrations.DeleteModel(
            name='AddressStatus',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='PersonStatus',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
