# Generated by Django 3.1.1 on 2020-09-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20200928_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstype',
            name='name',
            field=models.CharField(help_text='eg. private, business', max_length=255, verbose_name='Name for address type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='slug is human-readable, to make the referencing easier', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.ForeignKey(help_text='eg. active, moved, inactive', limit_choices_to={'category__slug': 'addressstatus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_email_status', to='person.term'),
        ),
        migrations.AlterField(
            model_name='legaltype',
            name='name',
            field=models.CharField(help_text='eg. Company, Church, Association', max_length=255, verbose_name='Name for legal type'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='gender',
            field=models.ForeignKey(help_text='eg. male, female, unknown', limit_choices_to={'category__slug': 'gender'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender', to='person.term'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='profession',
            field=models.CharField(help_text='e.g. nurse, carpenter', max_length=255, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='title',
            field=models.ForeignKey(help_text='eg. Herr, Frau, Frau Dr.', limit_choices_to={'category__slug': 'title'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title', to='person.term'),
        ),
        migrations.AlterField(
            model_name='person',
            name='abbreviation_key',
            field=models.CharField(default='', help_text='abbreviation of the name, for quick search of persons', max_length=255, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='connect_key',
            field=models.CharField(default='', help_text='This key can be communicated publically', max_length=255, verbose_name='Connect Key'),
        ),
        migrations.AlterField(
            model_name='person',
            name='legacy_key',
            field=models.CharField(default='', max_length=255, verbose_name='Legacy Key'),
        ),
        migrations.AlterField(
            model_name='person',
            name='salutation',
            field=models.CharField(help_text='eg. Frau, Firma', max_length=255, null=True, verbose_name='Salutation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='salutation_letter',
            field=models.CharField(help_text='eg. Liebe Angela, Sehr geehrte Frau Graber, Liebe Freunde, Sehr geehrte Damen und Herren,', max_length=255, null=True, verbose_name='Salutation Letter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.ForeignKey(help_text='eg. active, died, inactive', limit_choices_to={'category__slug': 'personstatus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personstatus', to='person.term'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.ForeignKey(help_text='eg. active, moved, inactive', limit_choices_to={'category__slug': 'addressstatus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_phone_status', to='person.term'),
        ),
        migrations.AlterField(
            model_name='phonetype',
            name='name',
            field=models.CharField(help_text='eg. landline, mobile, fax, direct dial', max_length=255, verbose_name='Name for phone type'),
        ),
        migrations.AlterField(
            model_name='postal',
            name='status',
            field=models.ForeignKey(help_text='eg. active, moved, inactive', limit_choices_to={'category__slug': 'addressstatus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_postal_status', to='person.term'),
        ),
    ]
