# Generated by Django 3.1.5 on 2021-03-09 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210309_1750"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallegalperson",
            name="primary_email_address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.email",
            ),
        ),
        migrations.AddField(
            model_name="historicalnaturalperson",
            name="primary_email_address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.email",
            ),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="primary_email_address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.email",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonassociation",
            name="primary_email_address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.email",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="primary_email_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_email_for",
                to="core.email",
            ),
        ),
    ]
