# Generated by Django 3.1.5 on 2021-01-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201215_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalperson',
            options={'ordering': ['name'], 'verbose_name': 'Legal Person', 'verbose_name_plural': 'Legal Persons'},
        ),
    ]
