# Generated by Django 3.1.5 on 2021-01-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_person_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='deleted',
        ),
    ]
