# Generated by Django 3.2.8 on 2021-12-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_term_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallegalperson',
            name='default_sorting_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Default Sorting Name'),
        ),
        migrations.AddField(
            model_name='historicalnaturalperson',
            name='default_sorting_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Default Sorting Name'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='default_sorting_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Default Sorting Name'),
        ),
        migrations.AddField(
            model_name='historicalpersonassociation',
            name='default_sorting_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Default Sorting Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='default_sorting_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Default Sorting Name'),
        ),
    ]
