# Generated by Django 3.2.8 on 2021-12-10 18:40

from django.db import migrations

import basxconnect.core.models.persons


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20211208_0920"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="legalperson",
            managers=[
                ("objects", basxconnect.core.models.persons.PersonManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="naturalperson",
            managers=[
                ("objects", basxconnect.core.models.persons.PersonManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="person",
            managers=[
                ("objects", basxconnect.core.models.persons.PersonManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="personassociation",
            managers=[
                ("objects", basxconnect.core.models.persons.PersonManager()),
            ],
        ),
    ]
