# Generated by Django 3.1.5 on 2021-01-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0027_historicallegalperson_historicalnaturalperson_historicalperson_historicalpersonassociation",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallegalperson",
            name="created",
        ),
        migrations.RemoveField(
            model_name="historicalnaturalperson",
            name="created",
        ),
        migrations.RemoveField(
            model_name="historicalperson",
            name="created",
        ),
        migrations.RemoveField(
            model_name="historicalpersonassociation",
            name="created",
        ),
        migrations.RemoveField(
            model_name="person",
            name="created",
        ),
        migrations.AddField(
            model_name="historicallegalperson",
            name="personnumber",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Person number"
            ),
        ),
        migrations.AddField(
            model_name="historicalnaturalperson",
            name="personnumber",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Person number"
            ),
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="personnumber",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Person number"
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonassociation",
            name="personnumber",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Person number"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="personnumber",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Person number"
            ),
        ),
        migrations.AlterField(
            model_name="historicallegalperson",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Display name"),
        ),
        migrations.AlterField(
            model_name="historicalnaturalperson",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Display name"),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Display name"),
        ),
        migrations.AlterField(
            model_name="historicalpersonassociation",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Display name"),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Display name"),
        ),
    ]
