# Generated by Django 3.1.5 on 2021-01-12 03:39

from django.db import migrations


class Migration(migrations.Migration):
    def convert_addresses(apps, _):
        PostalAddress = apps.get_model("core.Postal")
        POBox = apps.get_model("core.POBox")
        for address in POBox.objects.all():
            PostalAddress.objects.create(
                person=address.person,
                country=address.country,
                county=address.county,
                address=address.pobox_name,
                postcode=address.postcode,
                city=address.city,
                type=address.type,
                status=address.status,
            )

        for address in PostalAddress.objects.all():
            address.address = "\n".join(
                filter(
                    None,
                    [address.address, address.county, address.supplemental_address],
                )
            )
            address.save()

    dependencies = [
        ("core", "0031_auto_20210112_1039"),
    ]

    operations = [migrations.RunPython(convert_addresses, migrations.RunPython.noop)]
