# Generated by Django 3.1.5 on 2021-01-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_auto_20210112_1104"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pobox",
            name="county",
        ),
        migrations.RemoveField(
            model_name="pobox",
            name="person",
        ),
        migrations.RemoveField(
            model_name="pobox",
            name="status",
        ),
        migrations.RemoveField(
            model_name="pobox",
            name="type",
        ),
        migrations.RemoveField(
            model_name="postal",
            name="county",
        ),
        migrations.RemoveField(
            model_name="postal",
            name="supplemental_address",
        ),
        migrations.DeleteModel(
            name="County",
        ),
        migrations.DeleteModel(
            name="POBox",
        ),
    ]
