# Generated by Django 3.1.5 on 2021-01-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210112_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='categories',
            field=models.ManyToManyField(to='core.Term'),
        ),
    ]
