# Generated by Django 3.1.5 on 2021-01-16 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_person_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='person_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='core.person'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='core.person'),
        ),
    ]
