# Generated by Django 3.1.5 on 2021-01-25 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    def fill_person_number(apps, _):
        for model in [
            "historicalperson",
            "historicalnaturalperson",
            "historicallegalperson",
            "historicalpersonassociation",
            "person",
        ]:
            for i in apps.get_model(f"core.{model}").objects.all():
                i.personnumber = str(i.pk)
                i.save()

    dependencies = [
        ("core", "0038_auto_20210116_1723"),
    ]

    operations = [
        migrations.RunPython(fill_person_number, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="fax",
            name="type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category__slug": "phonetype"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.term",
            ),
        ),
        migrations.AlterField(
            model_name="historicallegalperson",
            name="personnumber",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Person number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalnaturalperson",
            name="personnumber",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Person number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalperson",
            name="personnumber",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Person number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpersonassociation",
            name="personnumber",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Person number"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="categories",
            field=models.ManyToManyField(blank=True, to="core.Term"),
        ),
        migrations.AlterField(
            model_name="person",
            name="personnumber",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="Person number"
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category__slug": "phonetype"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.term",
            ),
        ),
    ]
