# Generated by Django 3.1.5 on 2021-01-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_auto_20210125_0959"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationshiptype",
            name="reverse_name",
            field=models.CharField(
                blank=True,
                help_text="e.g. Person B has person A as a member",
                max_length=255,
                verbose_name="Backward name for relationship type",
            ),
        ),
        migrations.AlterField(
            model_name="relationshiptype",
            name="name",
            field=models.CharField(
                help_text="e.g. Person A is member of person B",
                max_length=255,
                verbose_name="Name for relationship type",
            ),
        ),
    ]
