# Generated by Django 3.1.5 on 2021-02-08 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20210208_1251"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhoneType",
        ),
        migrations.AlterField(
            model_name="web",
            name="type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category__slug": "urltype"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="type_core_web_list",
                to="core.term",
            ),
        ),
    ]
