# Generated by Django 3.1.5 on 2021-03-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_auto_20210210_1609"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallegalperson",
            name="_maintype",
            field=models.CharField(
                choices=[
                    ("person", "person"),
                    ("naturalperson", "naturalperson"),
                    ("legalperson", "legalperson"),
                    ("personassociation", "personassociation"),
                ],
                default="",
                editable=False,
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalnaturalperson",
            name="_maintype",
            field=models.CharField(
                choices=[
                    ("person", "person"),
                    ("naturalperson", "naturalperson"),
                    ("legalperson", "legalperson"),
                    ("personassociation", "personassociation"),
                ],
                default="",
                editable=False,
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalperson",
            name="_maintype",
            field=models.CharField(
                choices=[
                    ("person", "person"),
                    ("naturalperson", "naturalperson"),
                    ("legalperson", "legalperson"),
                    ("personassociation", "personassociation"),
                ],
                default="",
                editable=False,
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpersonassociation",
            name="_maintype",
            field=models.CharField(
                choices=[
                    ("person", "person"),
                    ("naturalperson", "naturalperson"),
                    ("legalperson", "legalperson"),
                    ("personassociation", "personassociation"),
                ],
                default="",
                editable=False,
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="_maintype",
            field=models.CharField(
                choices=[
                    ("person", "person"),
                    ("naturalperson", "naturalperson"),
                    ("legalperson", "legalperson"),
                    ("personassociation", "personassociation"),
                ],
                default="",
                editable=False,
                max_length=32,
            ),
            preserve_default=False,
        ),
    ]
