# Generated by Django 3.1.5 on 2021-03-04 08:16

from django.db import migrations


class Migration(migrations.Migration):
    def saveall(apps, _):
        for p in apps.get_model("core.NaturalPerson").objects.all():
            p._maintype = "naturalperson"
            p.save()
        for p in apps.get_model("core.LegalPerson").objects.all():
            p._maintype = "legalperson"
            p.save()
        for p in apps.get_model("core.PersonAssociation").objects.all():
            p._maintype = "personassociation"
            p.save()

    dependencies = [
        ("core", "0046_auto_20210304_1514"),
    ]

    operations = [migrations.RunPython(saveall, migrations.RunPython.noop)]
