# Generated by Django 3.1.5 on 2021-03-07 13:58

from django.db import migrations


class Migration(migrations.Migration):
    def saveall(apps, _):
        for p in apps.get_model("core.Person").objects.all():
            if hasattr(p, "core_postal_list"):
                if (
                    p.core_postal_list.all().count() == 1
                    or p.primary_postal_address is None
                ):
                    p.primary_postal_address = p.core_postal_list.first()
            else:
                p.primary_postal_address = None
            p.save()

    dependencies = [
        ("core", "0048_auto_20210307_2012"),
    ]

    operations = [migrations.RunPython(saveall, migrations.RunPython.noop)]
