# Generated by Django 3.2.4 on 2021-08-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_integration", "0002_interest_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="external_id",
            field=models.CharField(max_length=50),
        ),
    ]
