# Generated by Django 3.2.4 on 2021-11-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_integration", "0016_remove_synchronizationperson_successfully_added"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="synchronizationperson",
            name="message",
        ),
        migrations.AddField(
            model_name="synchronizationperson",
            name="sync_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "Newly added to BasxConnect"),
                    ("import_error", "Failed to add to BasxConnect"),
                    ("not_synced", "Previously synchronized but not this time"),
                ],
                max_length=255,
                verbose_name="Synchronization Status",
            ),
        ),
    ]
