# Generated by Django 3.2.4 on 2022-01-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_integration", "0020_subscription_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="deleted",
        ),
        migrations.AddField(
            model_name="subscription",
            name="active",
            field=models.BooleanField(
                blank=True, default=True, editable=False, verbose_name="Deleted"
            ),
        ),
    ]
