# Generated by Django 3.2.4 on 2022-05-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer_integration", "0022_auto_20220118_1308"),
    ]

    operations = [
        migrations.AddField(
            model_name="synchronizationperson",
            name="new_subscription_status",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="New subscription status"
            ),
        ),
        migrations.AddField(
            model_name="synchronizationperson",
            name="old_subscription_status",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Old subscription status"
            ),
        ),
        migrations.AlterField(
            model_name="synchronizationperson",
            name="sync_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "Newly added to BasxConnect"),
                    ("import_error", "Not added to BasxConnect"),
                    ("synced_previously", "Synchronized previously but not this time"),
                    ("subscription_status_changed", "Subscription status changed"),
                ],
                max_length=255,
                verbose_name="Synchronization Status",
            ),
        ),
    ]
